# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trompette', '0002_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(related_name='followed_by', to='trompette.Account'),
        ),
    ]
