# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('trompette', '0007_auto_20170521_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='in_reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='trompette.Status'),
        )
    ]
