# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def attach_thread(apps, schema_editor):
    Status = apps.get_model('trompette', 'Status')
    for status in Status.objects.filter(in_reply_to__isnull=True):
        status.thread_id = status.id
        status.save()
    for status in Status.objects.filter(in_reply_to__isnull=False):
        thread  = None
        current = status
        while True:
            if current.thread:
                thread = current.thread
                break
            current = current.in_reply_to
        status.thread_id = thread
        status.save()

class Migration(migrations.Migration):

    dependencies = [
        ('trompette', '0008_status_in_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trompette.Status'),
        ),
        migrations.RunPython(attach_thread, reverse_code=migrations.RunPython.noop)
    ]
