# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trompette', '0009_status_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='tags',
            field=models.ManyToManyField(related_name='statuses', to='trompette.Tag'),
        ),
    ]
