# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 22:36
from __future__ import unicode_literals
import re

from django.db import migrations


def get_hashtag(Tag, name):
    try:
        tag = Tag.objects.get(name=name)
    except Tag.DoesNotExist:
        tag = Tag(name=name)
        tag.save()
    return tag

def hashtags(apps, schema_editor):
    Status = apps.get_model('trompette', 'Status')
    Tag    = apps.get_model('trompette', 'Tag')

    for status in Status.objects.all():
        for name in re.findall('#(\w+)', status.content):
            tag = get_hashtag(Tag, name)
            status.tags.add(tag)
        status.save()

class Migration(migrations.Migration):

    dependencies = [
        ('trompette', '0010_auto_20170522_2236'),
    ]

    operations = [
        migrations.RunPython(hashtags, reverse_code=migrations.RunPython.noop)
    ]
