# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 19:58
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.timezone import now
import django.db.models.deletion

def populate_notifications(apps, schema_editor):
    Account      = apps.get_model('trompette', 'Account')
    Status       = apps.get_model('trompette', 'Status')
    Notification = apps.get_model('trompette', 'Notification')

    for status in Status.objects.all():
        if status.in_reply_to:
            mentioned = status.in_reply_to.account
            if status.account == mentioned:
                continue

            notification = Notification(account=mentioned, _type=1, mention=status, at=status.created_at)
            notification.save()
    for account in Account.objects.all():
        for target in account.following.all():
            notification = Notification(account=target, _type=2, follow=account, at=now())
            notification.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trompette', '0011_auto_20170522_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField()),
                ('_type', models.IntegerField(choices=[(1, 'mention'), (2, 'follow')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='trompette.Account')),
                ('follow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trompette.Account')),
                ('mention', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trompette.Status')),
            ],
        ),
        migrations.RunPython(populate_notifications, reverse_code=migrations.RunPython.noop)
    ]
